name: marvel_heroes
description: Um aplicativo Flutter para gerenciar heróis da Marvel usando MVVM.
version: 1.0.0
environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.2
  provider: ^6.1.1
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  cached_network_image: ^3.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
flutter:
  uses-material-design: true
